#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-client_java
Version  : 0.3.0
Release  : 1
URL      : https://github.com/prometheus/client_java/archive/parent-0.3.0.tar.gz
Source0  : https://github.com/prometheus/client_java/archive/parent-0.3.0.tar.gz
Source1  : https://repo1.maven.org/maven2/io/prometheus/parent/0.3.0/parent-0.3.0.pom
Source2  : https://repo1.maven.org/maven2/io/prometheus/simpleclient/0.3.0/simpleclient-0.3.0.jar
Source3  : https://repo1.maven.org/maven2/io/prometheus/simpleclient/0.3.0/simpleclient-0.3.0.pom
Source4  : https://repo1.maven.org/maven2/io/prometheus/simpleclient_common/0.3.0/simpleclient_common-0.3.0.jar
Source5  : https://repo1.maven.org/maven2/io/prometheus/simpleclient_common/0.3.0/simpleclient_common-0.3.0.pom
Source6  : https://repo1.maven.org/maven2/io/prometheus/simpleclient_httpserver/0.3.0/simpleclient_httpserver-0.3.0.jar
Source7  : https://repo1.maven.org/maven2/io/prometheus/simpleclient_httpserver/0.3.0/simpleclient_httpserver-0.3.0.pom
Source8  : https://repo1.maven.org/maven2/io/prometheus/simpleclient_pushgateway/0.3.0/simpleclient_pushgateway-0.3.0.jar
Source9  : https://repo1.maven.org/maven2/io/prometheus/simpleclient_pushgateway/0.3.0/simpleclient_pushgateway-0.3.0.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: mvn-client_java-data = %{version}-%{release}
Requires: mvn-client_java-license = %{version}-%{release}
BuildRequires : apache-maven
BuildRequires : buildreq-mvn

%description
# Prometheus JVM Client
It supports Java, Clojure, Scala, JRuby, and anything else that runs on the JVM.
[![Build Status](https://travis-ci.org/prometheus/client_java.png?branch=master)](https://travis-ci.org/prometheus/client_java)

%package data
Summary: data components for the mvn-client_java package.
Group: Data

%description data
data components for the mvn-client_java package.


%package license
Summary: license components for the mvn-client_java package.
Group: Default

%description license
license components for the mvn-client_java package.


%prep
%setup -q -n client_java-parent-0.3.0

%build

%install
mkdir -p %{buildroot}/usr/share/package-licenses/mvn-client_java
cp LICENSE %{buildroot}/usr/share/package-licenses/mvn-client_java/LICENSE
cp NOTICE %{buildroot}/usr/share/package-licenses/mvn-client_java/NOTICE
mkdir -p %{buildroot}/usr/share/java/.m2/repository/io/prometheus/parent/0.3.0
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/io/prometheus/parent/0.3.0/parent-0.3.0.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/io/prometheus/simpleclient/0.3.0
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/io/prometheus/simpleclient/0.3.0/simpleclient-0.3.0.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/io/prometheus/simpleclient/0.3.0
cp %{SOURCE3} %{buildroot}/usr/share/java/.m2/repository/io/prometheus/simpleclient/0.3.0/simpleclient-0.3.0.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/io/prometheus/simpleclient_common/0.3.0
cp %{SOURCE4} %{buildroot}/usr/share/java/.m2/repository/io/prometheus/simpleclient_common/0.3.0/simpleclient_common-0.3.0.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/io/prometheus/simpleclient_common/0.3.0
cp %{SOURCE5} %{buildroot}/usr/share/java/.m2/repository/io/prometheus/simpleclient_common/0.3.0/simpleclient_common-0.3.0.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/io/prometheus/simpleclient_httpserver/0.3.0
cp %{SOURCE6} %{buildroot}/usr/share/java/.m2/repository/io/prometheus/simpleclient_httpserver/0.3.0/simpleclient_httpserver-0.3.0.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/io/prometheus/simpleclient_httpserver/0.3.0
cp %{SOURCE7} %{buildroot}/usr/share/java/.m2/repository/io/prometheus/simpleclient_httpserver/0.3.0/simpleclient_httpserver-0.3.0.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/io/prometheus/simpleclient_pushgateway/0.3.0
cp %{SOURCE8} %{buildroot}/usr/share/java/.m2/repository/io/prometheus/simpleclient_pushgateway/0.3.0/simpleclient_pushgateway-0.3.0.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/io/prometheus/simpleclient_pushgateway/0.3.0
cp %{SOURCE9} %{buildroot}/usr/share/java/.m2/repository/io/prometheus/simpleclient_pushgateway/0.3.0/simpleclient_pushgateway-0.3.0.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/io/prometheus/parent/0.3.0/parent-0.3.0.pom
/usr/share/java/.m2/repository/io/prometheus/simpleclient/0.3.0/simpleclient-0.3.0.jar
/usr/share/java/.m2/repository/io/prometheus/simpleclient/0.3.0/simpleclient-0.3.0.pom
/usr/share/java/.m2/repository/io/prometheus/simpleclient_common/0.3.0/simpleclient_common-0.3.0.jar
/usr/share/java/.m2/repository/io/prometheus/simpleclient_common/0.3.0/simpleclient_common-0.3.0.pom
/usr/share/java/.m2/repository/io/prometheus/simpleclient_httpserver/0.3.0/simpleclient_httpserver-0.3.0.jar
/usr/share/java/.m2/repository/io/prometheus/simpleclient_httpserver/0.3.0/simpleclient_httpserver-0.3.0.pom
/usr/share/java/.m2/repository/io/prometheus/simpleclient_pushgateway/0.3.0/simpleclient_pushgateway-0.3.0.jar
/usr/share/java/.m2/repository/io/prometheus/simpleclient_pushgateway/0.3.0/simpleclient_pushgateway-0.3.0.pom

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/mvn-client_java/LICENSE
/usr/share/package-licenses/mvn-client_java/NOTICE
